version: '3.8'

services:
    postgres:
        image: postgres:15-alpine
        container_name: eventmanagement_postgres
        environment:
            POSTGRES_USER: eventuser
            POSTGRES_PASSWORD: eventpass123
            POSTGRES_DB: eventmanagement
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data

volumes:
    postgres_data: