version: "3.8"

services:
  backend:
    volumes:
      - dp_keys:/home/app/.aspnet/DataProtection-Keys
    build:
      context: ./backend
      dockerfile: EventManagement.Api/Dockerfile
    container_name: eventmanagement_backend
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      # Use the variable names exactly as they will appear in Azure
      - ConnectionStrings__DefaultConnection=Host=${DB_HOST};Port=${DB_PORT};Database=${DB_NAME};Username=${DB_USER};Password=${DB_PASS};SSL Mode=Require;Trust Server Certificate=true;Command Timeout=300
      - CORS__AllowedOrigins__0=${FRONTEND_URL}
      - Jwt__Key=${JWT_KEY}
      - Jwt__Issuer=${JWT_ISSUER}
      - Jwt__Audience=${JWT_AUDIENCE}
      - ASPNETCORE_HTTPS_PORT=7105
      - ASPNETCORE_URLS=http://+:8080
      - ASPNETCORE_HTTP_PORTS=8080
    ports:
      - "8080:8080" # Standardized cloud port
    networks:
      - event_net

volumes:
  dp_keys:

networks:
  event_net:
    driver: bridge